name: InputGenerator CI flow 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      
      - name: Build and Push Docker Image
        env:
          NAME: ${{secrets.DOCKERHUB_USERNAME}}
        run: |
          docker build -t $NAME/inputgen0:latest Dockerfile0
          docker push $NAME/inputgen0:latest

          docker build -t $NAME/inputgen1:latest Dockerfile1
          docker push $NAME/inputgen1:latest

          docker build -t $NAME/inputgen2:latest Dockerfile2
          docker push $NAME/inputgen2:latest

          docker build -t $NAME/inputgen3:latest Dockerfile3
          docker push $NAME/inputgen3:latest

          docker build -t $NAME/inputgen4:latest Dockerfile4
          docker push $NAME/inputgen4:latest
