name: InputGenerator CI Flow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Service InputGen
        env:
          NAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker build -t $NAME/inputgen0:latest ./service
          docker push $NAME/inputgen0:latest

      - name: Build & Push Auth InputGen
        env:
          NAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker build -t $NAME/inputgen4:latest ./auth
          docker push $NAME/inputgen4:latest

      - name: Build & Push Kmsg InputGen
        env:
          NAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker build -t $NAME/inputgen5:latest ./kmsg
          docker push $NAME/inputgen5:latest
